### PR TITLE
Add a "login" app (makes remote desktop easier)

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
The incantation to start a remote VNC server with this is something along the lines of:
```
ssh -T -L 5900:localhost:5900 octopull-desktop -- x11vnc -create -localhost -cursor none -env FD_PROG=egmde.login -env FD_GEOM=1920x1028 -env MIR_SERVER_X11_OUTPUT=1920x1028 -gone \'killall Xvfb\'
```

**Review by Saviq — CHANGES_REQUESTED** [review]
Forgot the `egmde.login` file?

**Comment by AlanGriffiths** [comment]
> Forgot the `egmde.login` file?

Snapd creates that as a link that launches the "app"
```
$ ls -lh `which egmde.login`
lrwxrwxrwx 1 root root 13 Mar 11 11:23 /snap/bin/egmde.login -> /usr/bin/snap
```

**Review by Saviq — APPROVED** [review]
Yeah. Shoulda read properly ;)

**Comment by Saviq** [comment]
bors merge

**Pull request merged**
