### PR TITLE
Hack wayland-sessions/egmde.desktop to work on Xenial

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Sorry, this got broken in transcription. Will fix later.

**Comment by AlanGriffiths** [comment]
OK, problems appear to be with the snapcraft toolchain, but leaving as "no-merge" until that's resolved.

https://forum.snapcraft.io/t/snapcraft-is-suddenly-unstable-cannot-identify-dependencies-and-has-unexpected-buffer-overflows/24071

**Comment by AlanGriffiths** [comment]
OK, the GHA build will use the (currently broken) snapcraft/stable, but I've updated the LP builds to use the (fixed) snapcraft/candidate.

We're good to land (but you need to build locally with snapcraft/candidate to test).

**Review by Saviq — APPROVED** [review]
Works.

bors merge

**Pull request merged**
