### PR TITLE
Improve install & post-refresh hooks

### LINKED ISSUE #32: install and post-refresh hooks segfault on 18.04 and Fedora

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Improve install & post-refresh hooks. (Fixes: #32)

### CODE REVIEW

**Comment by wmww** [comment]
Is the underlying problem that the system `dnf` is being run in the context of the snap? If so, shouldn't apt also be run in the system environment? Is "unset LD_LIBRARY_PATH" enough to fully simulate the system environment? Is this a job for [snap-out](https://github.com/wmww/snap-out)?

**Comment by AlanGriffiths** [comment]
On Mon, 5 Oct 2020 13:49:06 -0700, William Wold wrote:
> Is the underlying problem that the system `dnf` is being run in 
> the context of the snap? If so, shouldn't apt also be run in the 
> system environment? Is "unset LD_LIBRARY_PATH" enough to fully 
> simulate the system environment? Is this a job for 
> [snap-out](https://github.com/wmww/snap-out)?
>

No, it is `sh` that segfaults

-- 
Sent using Dekko from my Ubuntu device

**Comment by wmww** [comment]
Oh, most of my same questions still apply. Why is it crashing? If it's because it's an external binary being run in the context of the snap, snap-out is probably more reliable than unsetting specific variables.

**Comment by AlanGriffiths** [comment]
> Oh, most of my same questions still apply. Why is it crashing? If it's because it's an external binary being run in the context of the snap, snap-out is probably more reliable than unsetting specific variables.

I think that *not setting* environment variables is more acceptable than setting them, and engineering a way to unset them before running a shell script. There are no options to pass arguments to the `install` & `post-refresh` hooks, so this would entail writing an executable that uses `snapout` before launching a hard coded script to run as an `install`/`post-refresh` hook.

In any case, this solves the problem without introducing **new** issues. If you want to propose a better solution, we can discuss that in a corresponding PR.

**Review by wmww — APPROVED** [review]
LGTM, I now see that snap-out is not applicable here

**Pull request merged**
