### PR TITLE
Use apt-get and update repos before installing

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Why use apt-get? 

And why update repos?

**Comment by Saviq** [comment]
> Why use apt-get?

I cringe at:
> ```
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> ```


> And why update repos?

Cloud images have no apt cache, so if you install the snap through `cloud-init`, the install fails, not finding qtwayland5.

**Comment by AlanGriffiths** [comment]
> > And why update repos?
> 
> Cloud images have no apt cache, so if you install the snap through `cloud-init`, the install fails, not finding qtwayland5.

I'd prefer to carry on regardless of the install failure. This adds a significant install overhead to cover a corner-case that will likely not benefit: if the apt cache is empty, then it is very unlikely any Qt applications are installed.

**Comment by Saviq** [comment]
> I'd prefer to carry on regardless of the install failure. This adds a significant install overhead to cover a corner-case that will likely not benefit: if the apt cache is empty, then it is very unlikely any Qt applications are installed.

Should this be part of the `install` hook at all, then?

> This adds a significant install overhead

Only if there are no caches, I suppose. Otherwise it should be near NOOP?

**Comment by AlanGriffiths** [comment]
> Should this be part of the `install` hook at all, then?

Not sure. Since we force Qt apps to use the Wayland backend it seems polite to check it is installed, maybe something like

```
if apt policy libqt5gui5 | grep Installed; then apt --assume-yes install qtwayland5; fi
```

**Comment by Saviq** [comment]
> Not sure. Since we force Qt apps to use the Wayland backend it seems polite to check it is installed, maybe something like
> 
> ```
> if apt policy libqt5gui5 | grep Installed; then apt --assume-yes install qtwayland5; fi
> ```

That won't help people that only install Qt apps later… Maybe this is a bigger issue? Should `qtwayland5` be pulled in by qtbase5 these days?

**Comment by AlanGriffiths** [comment]
> Maybe this is a bigger issue? Should `qtwayland5` be pulled in by qtbase5 these days?

Well, Ubuntu desktop doesn't don't default to Wayland (yet). And this is getting OT for egmde-snap.

**Comment by Saviq** [comment]
I refreshed to the snap from `edge/pr43` and it only took 6s to run the post-refresh hook:

```plain
$ snap tasks 1949
Status  Spawn                      Ready                      Summary
...
Done    2021-01-20T18:23:42+01:00  2021-01-20T18:24:02+01:00  Run post-refresh hook of "egmde" snap if present
```

On a cloud system, where `apt-get update` would need to happen soon enough anyway:
```plain
$ snap tasks 1
Status  Spawn                      Ready                      Summary
...
Done    2021-01-20T17:33:53Z  2021-01-20T17:34:06Z  Run install hook of "core20" snap if present
```

So it took seconds for the snap to be available…

I'd leave it as-is, let me know.

**Comment by AlanGriffiths** [comment]
I don't think this is ideal, but neither is the status quo and I understand your reasoning.

bors r+

**Review by AlanGriffiths — APPROVED** [review]

**Pull request merged**
